
const data=window.MATCHA_DATA, PAGE_SIZE=40;let page=1,activeQuery='',filtered=[],matchedSearchItems=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').toLowerCase().replace(/[_:/-]+/g,' ').replace(/\s+/g,' ').trim();
let spoilerMode=data.spoilers.defaultMode,spoilerStage=data.spoilers.defaultStage;
try{spoilerMode=localStorage.getItem('matcha-spoiler-mode')||spoilerMode;spoilerStage=Number(localStorage.getItem('matcha-spoiler-stage'))||spoilerStage}catch{}
const spoilerLimit=()=>spoilerMode==='complete'?Infinity:spoilerMode==='minimal'?1:spoilerStage;
function spoilerAllowed(type,id){if(spoilerMode==='complete')return true;if((data.spoilers.hidden[type]||[]).includes(id))return false;return (data.spoilers.stages[type]?.[id]||1)<=spoilerLimit()}
function spoilerGate(type,id){const stage=data.spoilers.stages[type]?.[id];return `<div class="spoiler-gate"><b>Hidden by ${esc(spoilerMode)} spoiler mode</b>${stage?`This content unlocks at progression stage ${stage}.`:data.spoilers.policy}</div>`}
const spoilerModeControl=document.getElementById('spoiler-mode'),spoilerStageControl=document.getElementById('spoiler-stage');spoilerModeControl.value=spoilerMode;
function renderStageOptions(){spoilerStageControl.innerHTML=data.progression.map((stage,index)=>{const number=index+1,title=spoilerMode==='complete'||number<=spoilerStage?`${number}. ${stage.title}`:`Stage ${number}`;return `<option value="${number}">${esc(title)}</option>`}).join('');spoilerStageControl.value=spoilerStage}
function updateSpoilerControls(){renderStageOptions();spoilerStageControl.disabled=spoilerMode!=='progression';document.getElementById('spoiler-status').textContent=spoilerMode==='complete'?'All documented content is visible.':spoilerMode==='minimal'?'Only stage 1 and unclassified reference content are visible.':`Showing classified content through stage ${spoilerStage}.`}
spoilerModeControl.onchange=()=>{spoilerMode=spoilerModeControl.value;if(spoilerMode!=='progression'){spoilerStage=1;try{localStorage.setItem('matcha-spoiler-stage',spoilerStage)}catch{}}try{localStorage.setItem('matcha-spoiler-mode',spoilerMode)}catch{}updateSpoilerControls();refreshSpoilers()};spoilerStageControl.onchange=()=>{spoilerStage=Number(spoilerStageControl.value);try{localStorage.setItem('matcha-spoiler-stage',spoilerStage)}catch{}updateSpoilerControls();refreshSpoilers()};updateSpoilerControls();
const itemMatch=(x,q=activeQuery)=>q&&(norm(x.id).includes(q)||norm(x.name).includes(q));
function showPage(id,updateHash=true){document.querySelectorAll('.page').forEach(x=>{const active=x.id===id;x.classList.toggle('active',active);x.hidden=!active});document.querySelectorAll('.side button').forEach(x=>{const active=x.dataset.page===id;x.classList.toggle('active',active);x.ariaCurrent=active?'page':null});if(updateHash&&location.hash!==`#${id}`)location.hash=id;scrollTo(0,0);if(updateHash)document.getElementById('main-content').focus()}
document.querySelectorAll('.side button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
window.addEventListener('hashchange',()=>showPage(location.hash.slice(1)||'overview',false));
document.querySelectorAll('.stats').forEach(item=>{item.setAttribute('role','status');item.setAttribute('aria-live','polite')});
function slot(i,count=1){if(!i)return '<span class="slot"></span>';const visual=i.icon?`<img loading="lazy" src="${esc(i.icon)}" alt="${esc(i.name)}">`:`<span class="slot-fallback">${esc(i.name)}</span>`;return `<span class="slot" title="${esc(i.name)} (${esc(i.id)})">${visual}${count>1?`<span class="slot-count">${count}</span>`:''}</span>`}
function diagram(r){let input;if(r.type==='crafting_shaped'){const map={};r.ingredients.forEach(i=>map[i.symbol]=i);const rows=r.pattern.map(x=>x.padEnd(3,' '));while(rows.length<3)rows.push('   ');input=`<div class="craft-grid">${rows.flatMap(x=>[...x]).map(x=>slot(map[x])).join('')}</div>`}else if(r.type==='crafting_shapeless'){const items=[...r.ingredients];while(items.length<9)items.push(null);input=`<div class="craft-grid">${items.slice(0,9).map(i=>slot(i,i?.count)).join('')}</div>`}else input=`<div class="ingredients">${r.ingredients.map(i=>slot(i,i.count)).join('')}</div>`;return `<div class="visual-label">${esc(r.patternLabel)}</div><div class="recipe-visual">${input}<span class="arrow">➜</span>${slot({id:r.resultId,name:r.resultName,icon:r.icon},r.count)}</div>`}
function ingredient(i){return `<button class="ingredient ${itemMatch(i)?'matched':''}" data-lookup="${esc(i.id)}">${esc(i.name)}${i.count>1?' x'+i.count:''}</button>`}
function effectBadge(effect){const chance=effect.probability<1?` ${Math.round(effect.probability*100)}%`:'';return `<span class="effect ${esc(effect.category)}">${esc(effect.name)} ${effect.level} ${esc(effect.duration)}${chance}</span>`}
function foodBadges(food){if(!food)return '';const effects=food.effects.map(effectBadge);if(food.clearAll)effects.push('<span class="effect cleansing">Clears all effects</span>');if(food.removes.length)effects.push(`<span class="effect cleansing">Removes ${food.removes.length} harmful effects</span>`);return effects.length?`<div class="effect-badges">${effects.join('')}</div>`:''}
function foodDetails(food){if(!food)return '';const facts=[['Nutrition',food.nutrition??'Not specified'],['Saturation',food.saturation??'Not specified'],['Always edible',food.alwaysEdible?'Yes':'No'],['Consume time',food.consumeSeconds!=null?food.consumeSeconds+'s':'Default'],['Animation',food.animation||'Default'],['Remainder',food.remainder||'None']];const effects=food.effects.length?`<table class="effect-table"><tr><th>Effect</th><th>Level</th><th>Duration</th><th>Chance</th><th>Type</th></tr>${food.effects.map(e=>`<tr><td>${esc(e.name)}</td><td>${e.level}</td><td>${esc(e.duration)}</td><td>${Math.round(e.probability*100)}%</td><td><span class="effect ${esc(e.category)}">${esc(e.category)}</span></td></tr>`).join('')}</table>`:'<p>No status effects are applied.</p>';const cleansing=food.clearAll?'<p><span class="effect cleansing">Clears all active status effects</span></p>':food.removes.length?`<p><span class="effect cleansing">Removes:</span> ${food.removes.map(e=>esc(e.name)).join(', ')}</p>`:'';return `<section class="food-details"><h2>Food properties</h2><div class="food-facts">${facts.map(([k,v])=>`<div class="food-fact"><b>${esc(k)}</b>${esc(v)}</div>`).join('')}</div><h3>Effects when consumed</h3>${effects}${cleansing}</section>`}
function card(r){const resultMatch=itemMatch({id:r.resultId,name:r.resultName})?' matched':'',food=r.foodKey?foodByKey.get(r.foodKey):null;return `<article class="recipe"><img class="icon" loading="lazy" src="${esc(r.icon)}" alt=""><div class="result${resultMatch}"><b>${esc(r.resultName)}</b>${r.count>1?' x'+r.count:''} ${r.custom?'<span class="custom">custom item</span>':''}<div class="id">${esc(r.resultId)}</div>${foodBadges(food)}</div><div class="ingredients">${r.ingredients.map(ingredient).join('')}</div><div class="type">${esc(r.patternLabel)}<br><small>click for diagram and effects</small></div><div class="detail">${diagram(r)}${foodDetails(food)}<p><b>Recipe ID:</b> <code>${esc(r.id)}</code><br><b>Recipe type:</b> <code>${esc(r.type)}</code></p></div></article>`}
function wire(root){root.querySelectorAll('.recipe').forEach(x=>x.onclick=e=>{if(!e.target.closest('.ingredient'))x.classList.toggle('open')});root.querySelectorAll('.ingredient').forEach(x=>x.onclick=()=>{showPage('reverse');document.getElementById('reverse-search').value=x.dataset.lookup;reverse()})}
function searchItemHTML(item){const icon=item.icon||iconMap.get(item.id),key=item.key||item.id,id=item.underlyingId||item.id,food=item.foodKey?foodByKey.get(item.foodKey):null;return `<button class="search-item-card" data-obtain-id="${esc(key)}">${icon?`<img src="${esc(icon)}" alt="">`:''}<span><b>${esc(item.name)}</b><code>${esc(id)}</code>${foodBadges(food)}<small>View item information</small></span></button>`}
function wireSearchItems(root){root.querySelectorAll('.search-item-card').forEach(button=>button.onclick=()=>{showPage('obtaining');document.getElementById('obtain-search').value=button.dataset.obtainId;obtain()})}
function renderPage(){const start=(page-1)*PAGE_SIZE,end=start+PAGE_SIZE,root=document.getElementById('all-results');const items=matchedSearchItems.length?`<section class="matching-items"><h2>Matching items <span class="count">${matchedSearchItems.length}</span></h2>${matchedSearchItems.slice(0,20).map(searchItemHTML).join('')}</section>`:'';const recipes=filtered.slice(start,end).map(card).join('')||'<div class="empty">No matching recipes.</div>';root.innerHTML=items+recipes;wireSearchItems(root);wire(root);const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));document.getElementById('pager').innerHTML=`<button id="prev" ${page===1?'disabled':''}>Previous</button><span>Page ${page} of ${pages}</span><button id="next" ${page===pages?'disabled':''}>Next</button>`;document.getElementById('prev').onclick=()=>{page--;renderPage();scrollTo(0,0)};document.getElementById('next').onclick=()=>{page++;renderPage();scrollTo(0,0)}}
function search(){activeQuery=norm(document.getElementById('all-search').value);const category=document.getElementById('category').value;let pool=data.recipes.filter(r=>spoilerAllowed('recipe',r.id)&&(!category||r.namespace===category));if(activeQuery){matchedSearchItems=data.items.filter(item=>spoilerAllowed('item',item.key)&&(norm(item.id).includes(activeQuery)||norm(item.name).includes(activeQuery)||item.lore.some(line=>norm(line).includes(activeQuery))||item.properties.some(value=>norm(value).includes(activeQuery)))).sort((a,b)=>(norm(a.id)===activeQuery||norm(a.name)===activeQuery?-1:0)-(norm(b.id)===activeQuery||norm(b.name)===activeQuery?-1:0));const creates=pool.filter(r=>itemMatch({id:r.resultId,name:r.resultName}));const uses=pool.filter(r=>r.ingredients.some(i=>itemMatch(i))&&!creates.includes(r));const related=pool.filter(r=>norm(r.search).includes(activeQuery)&&!creates.includes(r)&&!uses.includes(r));filtered=[...creates,...uses,...related];document.getElementById('all-stats').textContent=`${matchedSearchItems.length} matching items; ${creates.length} recipes create them; ${uses.length} recipes use them; ${related.length} other matches.`}else{matchedSearchItems=[];filtered=pool;document.getElementById('all-stats').textContent=`${filtered.length.toLocaleString()} visible recipes. Only ${PAGE_SIZE} render at a time.`}page=1;renderPage()}
let timer;document.getElementById('all-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(search,150)};document.getElementById('category').onchange=search;document.getElementById('clear-all').onclick=()=>{document.getElementById('all-search').value='';document.getElementById('category').value='';search()};
function group(title,list,empty){const shown=list.slice(0,100),notice=list.length>100?`<div class="stats">Showing the first 100 exact or related matches. Refine the item name to narrow this list.</div>`:'';return `<section class="group"><h2>${title}<span class="count">${list.length} recipe${list.length===1?'':'s'}</span></h2>${notice}${shown.length?shown.map(card).join(''):`<div class="empty">${empty}</div>`}</section>`}
function reverse(){const raw=document.getElementById('reverse-search').value,q=norm(raw);if(!q)return;const exact=[...itemMap].find(([id,name])=>norm(id)===q||norm(name)===q),target=exact?.[0];activeQuery=target?norm(target):q;const matches=x=>target?x.id===target:itemMatch(x);const visibleRecipes=data.recipes.filter(r=>spoilerAllowed('recipe',r.id)),made=visibleRecipes.filter(r=>matches({id:r.resultId,name:r.resultName})),used=visibleRecipes.filter(r=>r.ingredients.some(matches));const root=document.getElementById('reverse-results');root.innerHTML=`<div class="reversehead"><b>${esc(raw)}</b>: produced by ${made.length}; used by ${used.length}.</div>`+group('Recipe for this item',made,'No visible recipe produces this item.')+group('Recipes using this item',used,'No visible recipe consumes this item.');wire(root)}
document.getElementById('reverse-go').onclick=reverse;document.getElementById('reverse-search').onkeydown=e=>{if(e.key==='Enter')reverse()};
const itemMap=new Map();
const canonical=id=>String(id).includes(':')?String(id):'minecraft:'+id;
const iconMap=new Map();data.recipes.forEach(r=>{if(r.icon)iconMap.set(canonical(r.resultId),r.icon);r.ingredients.forEach(i=>{if(i.icon)iconMap.set(canonical(i.id),i.icon)})});
const acquisitionMap=new Map(data.acquisition.map(item=>[item.id,item]));
const foodByKey=new Map(data.foodItems.map(item=>[item.key,item]));
const catalogByKey=new Map(data.items.map(item=>[item.key,item]));
function renderSpoilerDatalists(){itemMap.clear();data.recipes.filter(recipe=>spoilerAllowed('recipe',recipe.id)).forEach(r=>{itemMap.set(r.resultId,r.resultName);r.ingredients.forEach(i=>itemMap.set(i.id,i.name))});document.getElementById('item-list').innerHTML=[...itemMap].map(([id,name])=>`<option value="${esc(name)}">${esc(id)}</option>`).join('');document.getElementById('obtain-item-list').innerHTML=data.items.filter(item=>spoilerAllowed('item',item.key)).map(item=>`<option value="${esc(item.name)}">${esc(item.id)}</option>`).join('')}
function acquisitionSources(item){
 const recipes=item.recipes.length?`<h2>Recipes</h2><div class="source-list">${item.recipes.map(id=>`<div class="source"><b>Crafting or processing</b><code>${esc(id)}</code></div>`).join('')}</div>`:'';
 const loot=item.sources.length?`<h2>Loot and world sources</h2><div class="source-list">${item.sources.map(source=>`<div class="source"><b>${esc(source.kind)}</b>${esc(source.location)}<br><code>${esc(source.id)}</code></div>`).join('')}</div>`:'';
 const trades=item.trades.length?`<h2>Villager trades</h2><div class="source-list">${item.trades.map(trade=>`<div class="source"><b>${esc(trade.profession)} (${esc(trade.level)})</b>Cost: ${esc(trade.cost)}${trade.container?`<br>Contained in: ${esc(trade.container)}`:''}<br><code>${esc(trade.id)}</code></div>`).join('')}</div>`:'';
 const none=!item.recipes.length&&!item.sources.length&&!item.trades.length?'<div class="empty">No pack-defined acquisition source was found. This item may retain its normal vanilla source.</div>':'';
 const wiki=item.wiki?`<a class="wiki-link" href="${esc(item.wiki)}" target="_blank" rel="noopener">Open vanilla item on Minecraft Wiki</a>`:'';
 const icon=iconMap.get(item.id);
 return `<article class="acq-card"><div class="acq-head">${icon?`<img src="${esc(icon)}" alt="">`:''}<div><h2>${esc(item.name)}</h2><code>${esc(item.id)}</code></div></div>${recipes}${loot}${trades}${none}${wiki}</article>`
}
function foodAcquisition(item){const recipes=item.recipes.map(id=>data.recipes.find(recipe=>recipe.id===id)).filter(Boolean);return `<article class="acq-card"><div class="acq-head"><img src="${esc(item.icon)}" alt=""><div><h2>${esc(item.name)}</h2><code>${esc(item.underlyingId)}</code></div></div>${foodDetails(item)}<h2>How to make this item</h2><div class="food-item-recipes">${recipes.map(card).join('')}</div><p class="stats">This custom item uses ${esc(item.underlyingId)} as its underlying vanilla carrier. It is identified separately by its custom name, model, food properties, and consumable effects.</p></article>`}
function catalogItemPage(item){const acquisition=acquisitionMap.get(item.id),visibleSources=acquisition?.sources.filter(source=>spoilerAllowed('place',source.id))||[],visibleTrades=acquisition?.trades.filter(trade=>spoilerAllowed('trade',trade.id))||[],food=item.foodKey?foodByKey.get(item.foodKey):null,made=item.outputOf.map(id=>data.recipes.find(r=>r.id===id)).filter(r=>r&&spoilerAllowed('recipe',r.id)),used=item.usedIn.map(id=>data.recipes.find(r=>r.id===id)).filter(r=>r&&spoilerAllowed('recipe',r.id));const lore=item.lore.length?`<h2>In-game tooltip</h2><div class="item-lore">${item.lore.map(line=>`<p>${esc(line)}</p>`).join('')}</div>`:'';const properties=item.properties.length?`<h2>Item properties</h2><div class="item-properties">${item.properties.map(value=>`<span>${esc(value)}</span>`).join('')}</div>`:'';const loot=visibleSources.length?`<h2>Loot and world sources</h2><div class="source-list">${visibleSources.map(source=>`<div class="source"><b>${esc(source.kind)}</b>${esc(source.location)}<br><code>${esc(source.id)}</code></div>`).join('')}</div>`:'';const trades=visibleTrades.length?`<h2>Villager trades</h2><div class="source-list">${visibleTrades.map(trade=>`<div class="source"><b>${esc(trade.profession)} (${esc(trade.level)})</b>Cost: ${esc(trade.cost)}${trade.container?`<br>Contained in: ${esc(trade.container)}`:''}<br><code>${esc(trade.id)}</code></div>`).join('')}</div>`:'';const madeSection=`<h2>Made by <span class="count">${made.length}</span></h2>${made.length?made.slice(0,40).map(card).join(''):'<div class="empty">No visible pack recipe creates this exact item variant.</div>'}`;const usedSection=`<h2>Used in <span class="count">${used.length}</span></h2>${used.length?used.slice(0,40).map(card).join(''):'<div class="empty">No visible pack recipe consumes this item.</div>'}`;const wiki=acquisition?.wiki?`<a class="wiki-link" href="${esc(acquisition.wiki)}" target="_blank" rel="noopener">Open vanilla item on Minecraft Wiki</a>`:'';return `<article class="acq-card"><div class="acq-head">${item.icon?`<img src="${esc(item.icon)}" alt="">`:''}<div><h2>${esc(item.name)}</h2><code>${esc(item.id)}</code><div>${esc(item.category)}${item.custom?' | custom variant':''}</div></div></div>${lore}${properties}${food?foodDetails(food):''}${madeSection}${usedSection}${loot}${trades}${wiki}</article>`}
function openCatalogItem(key){const item=catalogByKey.get(key);if(!item)return;showPage('obtaining');document.getElementById('obtain-search').value=item.name;const root=document.getElementById('obtain-results');root.innerHTML=spoilerAllowed('item',item.key)?catalogItemPage(item):spoilerGate('item',item.key);wire(root)}
function wireAcquisitionChoices(root){root.querySelectorAll('.item-choice').forEach(button=>button.onclick=()=>{document.getElementById('obtain-search').value=button.dataset.id;obtain()})}
function obtain(){
 const raw=document.getElementById('obtain-search').value.trim(),q=norm(raw);if(!q)return;
 const exactItem=catalogByKey.get(raw)||catalogByKey.get(`base:${canonical(raw)}`)||data.items.find(item=>norm(item.name)===q);
 const root=document.getElementById('obtain-results');
 if(exactItem){root.innerHTML=spoilerAllowed('item',exactItem.key)?catalogItemPage(exactItem):spoilerGate('item',exactItem.key);wire(root);return}
 const matches=data.items.filter(item=>spoilerAllowed('item',item.key)&&(norm(item.id).includes(q)||norm(item.name).includes(q))).slice(0,100).map(item=>({id:item.key,name:item.name,detail:item.id}));
 root.innerHTML=matches.length?`<div class="reversehead">${matches.length} matching items. Select one for its acquisition details.</div>${matches.map(item=>`<button class="item-choice" data-id="${esc(item.id)}"><b>${esc(item.name)}</b><br><code>${esc(item.detail)}</code></button>`).join('')}`:'<div class="empty">No matching item was found.</div>';
 wireAcquisitionChoices(root)
}
document.getElementById('obtain-go').onclick=obtain;document.getElementById('obtain-search').onkeydown=e=>{if(e.key==='Enter')obtain()};
let tradePage=1,tradeFiltered=data.trades;const TRADE_PAGE_SIZE=40;
function tradeItem(item){const icon=item.icon||iconMap.get(item.id),count=item.count===1?'':`${esc(item.count)} `;return `<span class="trade-item">${icon?`<img loading="lazy" src="${esc(icon)}" alt="">`:''}<span><b>${count}${esc(item.name)}</b><code>${esc(item.id)}</code></span></span>`}
function tradeCard(trade){const contents=trade.bundleContents.length?`<details class="trade-contents"><summary>Bundle contents (${trade.bundleContents.length})</summary><div class="trade-items">${trade.bundleContents.map(tradeItem).join('')}</div></details>`:'';const facts=[['Maximum uses',trade.maxUses??'Not specified'],['Villager XP',trade.xp??'Not specified'],['Reputation discount',trade.reputationDiscount??'Not specified']];return `<article class="trade-card"><div class="trade-heading"><div><strong>${esc(trade.profession)}</strong><span>${esc(trade.level)}</span></div><code>${esc(trade.id)}</code></div><div class="trade-exchange"><div class="trade-items">${trade.costs.map(tradeItem).join('')||'<span>Pack-defined cost</span>'}</div><span class="trade-arrow">➜</span>${tradeItem(trade.result)}</div>${contents}<div class="trade-facts">${facts.map(([key,value])=>`<div><b>${esc(key)}</b>${esc(value)}</div>`).join('')}</div><p class="provenance">${esc(trade.source)}</p></article>`}
function renderTrades(){const start=(tradePage-1)*TRADE_PAGE_SIZE,pages=Math.max(1,Math.ceil(tradeFiltered.length/TRADE_PAGE_SIZE));document.getElementById('trade-results').innerHTML=tradeFiltered.slice(start,start+TRADE_PAGE_SIZE).map(tradeCard).join('')||'<div class="empty">No trades match these filters.</div>';document.getElementById('trade-stats').textContent=`Showing ${tradeFiltered.length} of ${data.trades.length} pack-defined trades`;document.getElementById('trade-pager').innerHTML=`<button id="trade-prev" ${tradePage===1?'disabled':''}>Previous</button><span>Page ${tradePage} of ${pages}</span><button id="trade-next" ${tradePage===pages?'disabled':''}>Next</button>`;document.getElementById('trade-prev').onclick=()=>{tradePage--;renderTrades();scrollTo(0,0)};document.getElementById('trade-next').onclick=()=>{tradePage++;renderTrades();scrollTo(0,0)}}
function filterTrades(){const q=norm(document.getElementById('trade-search').value),profession=document.getElementById('trade-profession').value,level=document.getElementById('trade-level').value;tradeFiltered=data.trades.filter(trade=>spoilerAllowed('trade',trade.id)&&(!profession||trade.profession===profession)&&(!level||trade.level===level)&&(!q||[trade.id,trade.profession,trade.level,trade.result.id,trade.result.name,...trade.costs.flatMap(item=>[item.id,item.name]),...trade.bundleContents.flatMap(item=>[item.id,item.name])].some(value=>norm(value).includes(q))));tradePage=1;renderTrades()}
const tradeProfessions=[...new Set(data.trades.map(trade=>trade.profession))].sort(),tradeLevels=['Novice','Apprentice','Journeyman','Expert','Master','Any'].filter(level=>data.trades.some(trade=>trade.level===level));document.getElementById('trade-profession').innerHTML+=tradeProfessions.map(value=>`<option value="${esc(value)}">${esc(value)}</option>`).join('');document.getElementById('trade-level').innerHTML+=tradeLevels.map(value=>`<option value="${esc(value)}">${esc(value)}</option>`).join('');document.getElementById('trade-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(filterTrades,150)};document.getElementById('trade-profession').onchange=filterTrades;document.getElementById('trade-level').onchange=filterTrades;document.getElementById('clear-trades').onclick=()=>{document.getElementById('trade-search').value='';document.getElementById('trade-profession').value='';document.getElementById('trade-level').value='';filterTrades()};
const allPlaces=[...data.places.structures,...data.places.locations];let placePage=1,placeFiltered=allPlaces;const PLACE_PAGE_SIZE=30;
function placeItem(item){const catalog=data.items.find(candidate=>candidate.id===item.id),icon=item.icon||catalog?.icon||iconMap.get(item.id);return `<button class="place-item open-catalog-item" data-item-key="${esc(catalog?.key||'')}">${icon?`<img loading="lazy" src="${esc(icon)}" alt="">`:''}<span><b>${esc(item.name)}</b><code>${esc(item.id)}</code></span></button>`}
function structureCard(item){const placement=item.placement,placementFacts=placement?`<h3>Placement</h3><div class="place-facts">${[['Set',placement.setId],['Type',placement.type],['Spacing',placement.spacing],['Separation',placement.separation],['Salt',placement.salt]].filter(([,value])=>value!=null).map(([key,value])=>`<div><b>${esc(key)}</b>${esc(value)}</div>`).join('')}</div>`:'';const biomes=item.biomes.length?item.biomes.map(value=>`<code>${esc(value)}</code>`).join(''):item.biomeSelector?`<code>${esc(item.biomeSelector)}</code>`:'Not specified';return `<article class="place-card"><div class="place-heading"><span class="place-kind">${esc(item.kind)}</span><h2>${esc(item.name)}</h2><code>${esc(item.id)}</code></div><div class="place-facts">${[['Structure type',item.type],['Generation step',item.step],['Terrain adaptation',item.terrainAdaptation],['Start pool',item.startPool],['Jigsaw size',item.size],['Maximum distance',item.maxDistance]].filter(([,value])=>value!=null).map(([key,value])=>`<div><b>${esc(key)}</b>${esc(value)}</div>`).join('')}</div><h3>Biomes</h3><div class="biome-list">${biomes}</div>${placementFacts}<p class="provenance">${esc(item.source)}</p></article>`}
function lootPlaceCard(item){return `<article class="place-card"><div class="place-heading"><span class="place-kind">${esc(item.kind)}</span><h2>${esc(item.name)}</h2><code>${esc(item.id)}</code></div><details class="place-loot" open><summary>${item.items.length} obtainable item${item.items.length===1?'':'s'}</summary><div class="place-items">${item.items.map(placeItem).join('')}</div></details><p class="provenance">${esc(item.source)}</p></article>`}
function placeCard(item){return item.kind==='Structure definition'?structureCard(item):lootPlaceCard(item)}
function wirePlaces(root){root.querySelectorAll('.open-catalog-item').forEach(button=>button.onclick=()=>{if(button.dataset.itemKey)openCatalogItem(button.dataset.itemKey)})}
function renderPlaces(){const start=(placePage-1)*PLACE_PAGE_SIZE,pages=Math.max(1,Math.ceil(placeFiltered.length/PLACE_PAGE_SIZE)),root=document.getElementById('place-results');root.innerHTML=placeFiltered.slice(start,start+PLACE_PAGE_SIZE).map(placeCard).join('')||'<div class="empty">No places match these filters.</div>';wirePlaces(root);document.getElementById('place-stats').textContent=`Showing ${placeFiltered.length} of ${allPlaces.length} source-backed place records (${data.places.structures.length} structures, ${data.places.locations.length} loot locations)`;document.getElementById('place-pager').innerHTML=`<button id="place-prev" ${placePage===1?'disabled':''}>Previous</button><span>Page ${placePage} of ${pages}</span><button id="place-next" ${placePage===pages?'disabled':''}>Next</button>`;document.getElementById('place-prev').onclick=()=>{placePage--;renderPlaces();scrollTo(0,0)};document.getElementById('place-next').onclick=()=>{placePage++;renderPlaces();scrollTo(0,0)}}
function filterPlaces(){const q=norm(document.getElementById('place-search').value),kind=document.getElementById('place-kind').value;placeFiltered=allPlaces.filter(item=>spoilerAllowed('place',item.id)&&(!kind||item.kind===kind)&&(!q||[item.name,item.id,item.kind,item.type,item.step,item.terrainAdaptation,item.startPool,item.biomeSelector,...(item.biomes||[]),...(item.items||[]).flatMap(entry=>[entry.id,entry.name])].some(value=>norm(value).includes(q))));placePage=1;renderPlaces()}
document.getElementById('place-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(filterPlaces,150)};document.getElementById('place-kind').onchange=filterPlaces;document.getElementById('clear-places').onclick=()=>{document.getElementById('place-search').value='';document.getElementById('place-kind').value='';filterPlaces()};
function archaeologyVisual(item){return `<span class="archaeology-item">${item.icon?`<img loading="lazy" src="${esc(item.icon)}" alt="">`:''}<span><b>${esc(item.name)}</b><code>${esc(item.id)}</code></span></span>`}
function archaeologyEntry(entry){const resolved=entry.resolvedItems.length?`<details><summary>${entry.resolvedItems.length} possible nested item${entry.resolvedItems.length===1?'':'s'}</summary><div class="archaeology-resolved">${entry.resolvedItems.map(archaeologyVisual).join('')}</div></details>`:'';return `<div class="archaeology-entry"><span class="entry-kind">${esc(entry.kind)}</span>${archaeologyVisual(entry)}<div class="entry-stats"><span>Weight ${esc(entry.weight)}</span><span>Quality ${esc(entry.quality)}</span>${entry.baseChance!=null?`<span>${esc(entry.baseChance)}% base share</span>`:''}${entry.conditional?'<span>Conditional</span>':''}</div>${resolved}</div>`}
function archaeologyCard(site){return `<article class="archaeology-card"><div class="place-heading"><span class="place-kind">Archaeology loot table</span><h2>${esc(site.name)}</h2><code>${esc(site.id)}</code></div><div class="place-facts"><div><b>Table type</b>${esc(site.tableType||'Not specified')}</div><div><b>Pool rolls</b>${site.rolls.map(esc).join(', ')}</div><div><b>Direct entries</b>${site.entries.length}</div></div><div class="archaeology-entries">${site.entries.map(archaeologyEntry).join('')}</div><p class="provenance">${esc(site.source)}</p></article>`}
function wireArchaeology(root){wirePlaces(root)}
function renderArchaeology(){const q=norm(document.getElementById('archaeology-search').value),sites=data.archaeology.filter(site=>!q||[site.name,site.id,site.tableType,...site.entries.flatMap(entry=>[entry.name,entry.id,...entry.resolvedItems.flatMap(item=>[item.name,item.id])])].some(value=>norm(value).includes(q)));const root=document.getElementById('archaeology-results');root.innerHTML=sites.map(archaeologyCard).join('')||'<div class="empty">No archaeology tables match this search.</div>';wireArchaeology(root);document.getElementById('archaeology-stats').textContent=`Showing ${sites.length} of ${data.archaeology.length} archaeology loot tables`}
document.getElementById('archaeology-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(renderArchaeology,150)};document.getElementById('clear-archaeology').onclick=()=>{document.getElementById('archaeology-search').value='';renderArchaeology()};
function fishingEntry(entry){const resolved=entry.resolvedItems.length?`<details><summary>${entry.resolvedItems.length} possible item${entry.resolvedItems.length===1?'':'s'}</summary><div class="archaeology-resolved">${entry.resolvedItems.map(archaeologyVisual).join('')}</div></details>`:'';const modifiers=entry.modifiers.length?`<div class="entry-modifiers">${entry.modifiers.map(value=>`<span>${esc(value)}</span>`).join('')}</div>`:'';return `<div class="fishing-entry"><span class="entry-kind">${esc(entry.kind)}</span>${archaeologyVisual(entry)}<div class="entry-stats"><span>Weight ${esc(entry.weight)}</span><span>Quality ${esc(entry.quality)}</span>${entry.baseChance!=null?`<span>${esc(entry.baseChance)}% table share</span>`:''}</div>${entry.conditions.length?`<div class="condition-list">${entry.conditions.map(value=>`<span>${esc(value)}</span>`).join('')}</div>`:''}${modifiers}${resolved}</div>`}
function fishingEligibility(record){if(!record.active)return '<div class="condition-list"><span>Not referenced by the active fishing router</span></div>';if(record.globalBiomes)return '<div class="condition-list"><span>All biomes</span></div>';const selectors=record.biomeSelectors.length?`<div class="condition-list">${record.biomeSelectors.map(value=>`<span>${esc(value)}</span>`).join('')}</div>`:'';const biomes=record.biomes.length?`<details class="fishing-biomes"><summary>${record.biomes.length} eligible biome${record.biomes.length===1?'':'s'}</summary><div class="biome-list">${record.biomes.map(value=>`<code>${esc(value)}</code>`).join('')}</div></details>`:'';return selectors+biomes}
function fishingRecordCard(record){const eligibility=fishingEligibility(record);if(record.role==='Species'&&record.entries.length===1){const entry=record.entries[0];return `<article class="species-card"><div><span class="place-kind">${esc(record.role)}</span><h3>${esc(record.name)}</h3><code>${esc(record.id)}</code>${eligibility}</div>${fishingEntry(entry)}<p class="provenance">${esc(record.source)}</p></article>`}return `<article class="fishing-card"><div class="place-heading"><span class="place-kind">${esc(record.role)}</span><h2>${esc(record.name)}</h2><code>${esc(record.id)}</code></div>${eligibility}<div class="fishing-entries">${record.entries.map(fishingEntry).join('')}</div><p class="provenance">${esc(record.source)}</p></article>`}
function renderFishingRoutes(){document.getElementById('fishing-routes').innerHTML=data.fishing.routes.map(entry=>`<article class="route-card"><b>${esc(entry.name)}</b><code>${esc(entry.id)}</code><div class="entry-stats"><span>Weight ${esc(entry.weight)}</span><span>Quality ${esc(entry.quality)}</span></div>${entry.conditions.length?`<div class="condition-list">${entry.conditions.map(value=>`<span>${esc(value)}</span>`).join('')}</div>`:'<div class="condition-list"><span>Always eligible</span></div>'}</article>`).join('')}
let fishingPage=1,fishingFiltered=data.fishing.tables;const FISHING_PAGE_SIZE=20;
function wireFishing(root){wirePlaces(root)}
function renderFishing(){const start=(fishingPage-1)*FISHING_PAGE_SIZE,pages=Math.max(1,Math.ceil(fishingFiltered.length/FISHING_PAGE_SIZE)),root=document.getElementById('fishing-results');root.innerHTML=fishingFiltered.slice(start,start+FISHING_PAGE_SIZE).map(fishingRecordCard).join('')||'<div class="empty">No fishing content matches these filters.</div>';wireFishing(root);document.getElementById('fishing-stats').textContent=`Showing ${fishingFiltered.length} of ${data.fishing.tables.length} fishing tables`;document.getElementById('fishing-pager').innerHTML=`<button id="fishing-prev" ${fishingPage===1?'disabled':''}>Previous</button><span>Page ${fishingPage} of ${pages}</span><button id="fishing-next" ${fishingPage===pages?'disabled':''}>Next</button>`;document.getElementById('fishing-prev').onclick=()=>{fishingPage--;renderFishing();scrollTo(0,0)};document.getElementById('fishing-next').onclick=()=>{fishingPage++;renderFishing();scrollTo(0,0)}}
function filterFishing(){const q=norm(document.getElementById('fishing-search').value),role=document.getElementById('fishing-role').value;fishingFiltered=data.fishing.tables.filter(record=>(!role||record.role===role)&&(!q||[record.name,record.id,record.role,...record.biomeSelectors,...record.biomes,...record.entries.flatMap(entry=>[entry.name,entry.id,...entry.conditions,...entry.modifiers,...entry.resolvedItems.flatMap(item=>[item.name,item.id])])].some(value=>norm(value).includes(q))));fishingPage=1;renderFishing()}
document.getElementById('fishing-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(filterFishing,150)};document.getElementById('fishing-role').onchange=filterFishing;document.getElementById('clear-fishing').onclick=()=>{document.getElementById('fishing-search').value='';document.getElementById('fishing-role').value='';filterFishing()};
let foodPage=1,foodFiltered=data.foodItems;const FOOD_PAGE_SIZE=24;
function foodCard(item){return `<article class="food-card"><button class="food-item-link food-image-link" data-food-key="${esc(item.key)}" title="Open ${esc(item.name)} item page"><img loading="lazy" src="${esc(item.icon)}" alt="${esc(item.name)}"></button><div><button class="food-item-link food-name-link" data-food-key="${esc(item.key)}">${esc(item.name)}</button><div class="id">${esc(item.underlyingId)}</div><div class="stats">${item.recipes.length} recipe${item.recipes.length===1?'':'s'}</div></div><div>${foodBadges(item)}<details><summary>Quick food properties</summary>${foodDetails(item)}</details></div></article>`}
function openFoodItem(key){openCatalogItem(key)}
function wireFoodLinks(root){root.querySelectorAll('.food-item-link').forEach(link=>link.onclick=()=>openFoodItem(link.dataset.foodKey))}
function renderFoods(){const start=(foodPage-1)*FOOD_PAGE_SIZE,pages=Math.max(1,Math.ceil(foodFiltered.length/FOOD_PAGE_SIZE)),root=document.getElementById('food-results');root.innerHTML=foodFiltered.slice(start,start+FOOD_PAGE_SIZE).map(foodCard).join('')||'<div class="empty">No foods match these filters.</div>';wireFoodLinks(root);document.getElementById('food-stats').textContent=`Showing ${foodFiltered.length} of ${data.foodItems.length} distinct food variants`;document.getElementById('food-pager').innerHTML=`<button id="food-prev" ${foodPage===1?'disabled':''}>Previous</button><span>Page ${foodPage} of ${pages}</span><button id="food-next" ${foodPage===pages?'disabled':''}>Next</button>`;document.getElementById('food-prev').onclick=()=>{foodPage--;renderFoods();scrollTo(0,0)};document.getElementById('food-next').onclick=()=>{foodPage++;renderFoods();scrollTo(0,0)}}
function filterFoods(){const q=norm(document.getElementById('food-search').value),effect=document.getElementById('effect-filter').value,kind=document.getElementById('effect-kind').value;foodFiltered=data.foodItems.filter(item=>(!q||norm(item.name).includes(q)||norm(item.underlyingId).includes(q)||item.effects.some(e=>norm(e.name).includes(q))||item.removes.some(e=>norm(e.name).includes(q)))&&(!effect||item.effects.some(e=>e.id===effect))&&(!kind||(kind==='cleansing'?(item.clearAll||item.removes.length):item.effects.some(e=>e.category===kind))));foodPage=1;renderFoods()}
document.getElementById('effect-filter').innerHTML+=data.foodEffects.map(([id,name])=>`<option value="${esc(id)}">${esc(name)}</option>`).join('');document.getElementById('food-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(filterFoods,150)};document.getElementById('effect-filter').onchange=filterFoods;document.getElementById('effect-kind').onchange=filterFoods;document.getElementById('clear-food').onclick=()=>{document.getElementById('food-search').value='';document.getElementById('effect-filter').value='';document.getElementById('effect-kind').value='';filterFoods()};
let itemPage=1,itemFiltered=data.items;const ITEM_PAGE_SIZE=48;
function catalogCard(item){return `<button class="catalog-item" data-item-key="${esc(item.key)}">${item.icon?`<img loading="lazy" src="${esc(item.icon)}" alt="">`:''}<span><b>${esc(item.name)}</b><code>${esc(item.id)}</code><small>${esc(item.category)}${item.custom?' | custom variant':''}</small></span></button>`}
function wireCatalog(root){root.querySelectorAll('.catalog-item').forEach(button=>button.onclick=()=>openCatalogItem(button.dataset.itemKey))}
function renderItems(){const start=(itemPage-1)*ITEM_PAGE_SIZE,pages=Math.max(1,Math.ceil(itemFiltered.length/ITEM_PAGE_SIZE)),root=document.getElementById('item-results');root.innerHTML=itemFiltered.slice(start,start+ITEM_PAGE_SIZE).map(catalogCard).join('')||'<div class="empty">No items match these filters.</div>';wireCatalog(root);document.getElementById('item-stats').textContent=`Showing ${itemFiltered.length} of ${data.items.length} item entries`;document.getElementById('item-pager').innerHTML=`<button id="item-prev" ${itemPage===1?'disabled':''}>Previous</button><span>Page ${itemPage} of ${pages}</span><button id="item-next" ${itemPage===pages?'disabled':''}>Next</button>`;document.getElementById('item-prev').onclick=()=>{itemPage--;renderItems();scrollTo(0,0)};document.getElementById('item-next').onclick=()=>{itemPage++;renderItems();scrollTo(0,0)}}
function filterItems(){const q=norm(document.getElementById('item-search').value),category=document.getElementById('item-category').value;itemFiltered=data.items.filter(item=>spoilerAllowed('item',item.key)&&(!category||item.category===category)&&(!q||norm(item.name).includes(q)||norm(item.id).includes(q)||item.lore.some(line=>norm(line).includes(q))||item.properties.some(value=>norm(value).includes(q))));itemPage=1;renderItems()}
const itemCategories=[...new Set(data.items.map(item=>item.category))].sort();document.getElementById('item-category').innerHTML+=itemCategories.map(value=>`<option value="${esc(value)}">${esc(value)}</option>`).join('');document.getElementById('item-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(filterItems,150)};document.getElementById('item-category').onchange=filterItems;document.getElementById('clear-items').onclick=()=>{document.getElementById('item-search').value='';document.getElementById('item-category').value='';filterItems()};
const enchantmentById=new Map(data.enchantments.map(item=>[item.id,item]));
function enchantmentCard(item){const facts=[['Maximum level',item.max],['Slots',item.slots.join(', ')||'Not specified'],['Weight',item.weight??'Not specified'],['Anvil cost',item.anvilCost??'Not specified'],['Triggers',item.effectTriggers.map(x=>x.replace('minecraft:','').replaceAll('_',' ')).join(', ')||'None']];const supported=item.items.length?`<h3>Compatible equipment</h3><div class="related-buttons">${item.items.map(id=>{const icon=iconMap.get(canonical(id));return `<button class="open-base-item" data-item-id="${esc(canonical(id))}">${icon?`<img loading="lazy" src="${esc(icon)}" alt="">`:''}${esc(id.replace('minecraft:','').replaceAll('_',' '))}</button>`}).join('')}</div>`:'';const equipment=item.equipment.length?`<h3>Equipment carrying this enchantment</h3><div class="related-buttons">${item.equipment.map(entry=>`<button class="open-catalog-item" data-item-key="${esc(entry.itemKey)}">${entry.icon?`<img loading="lazy" src="${esc(entry.icon)}" alt="">`:''}${esc(entry.name)} ${entry.level>1?' '+entry.level:''}</button>`).join('')}</div>`:'';const visibleBlessings=item.blessings.filter(entry=>spoilerAllowed('blessing',entry.id)),blessings=visibleBlessings.length?`<h3>Included in Blessings</h3><div class="related-buttons">${visibleBlessings.map(entry=>`<button class="open-blessing" data-blessing-id="${esc(entry.id)}">${esc(entry.name)} ${entry.level>1?' '+entry.level:''}</button>`).join('')}</div>`:'';const technical=item.functions.length?`<details class="technical"><summary>Technical function commands</summary>${item.functions.map(fn=>`<h4>${esc(fn.id)}</h4><pre>${esc(fn.commands.join('\\n'))}</pre><div class="provenance">${esc(fn.source)}</div>`).join('')}</details>`:'';return `<details class="enchant-card"><summary><strong>${esc(item.name)}</strong><span>${esc(item.summary||'Custom enchantment')}</span><code>${esc(item.id)}</code></summary><div class="enchant-body">${item.inGameName&&item.inGameName!==item.name?`<p><b>In-game display:</b> ${esc(item.inGameName)}</p>`:''}<p>${esc(item.summary||'No reviewed behavior summary is available.')}</p>${item.activation?`<p><b>Activation:</b> ${esc(item.activation)}</p>`:''}${item.scaling?`<p><b>Scaling:</b> ${esc(item.scaling)}</p>`:''}<div class="enchant-facts">${facts.map(([key,value])=>`<div class="enchant-fact"><b>${esc(key)}</b>${esc(value)}</div>`).join('')}</div>${supported}${equipment}${blessings}${technical}<p class="provenance">${esc(item.provenance)} | ${esc(item.source)}</p></div></details>`}
function wireEnchantments(root){root.querySelectorAll('.open-catalog-item').forEach(button=>button.onclick=()=>openCatalogItem(button.dataset.itemKey));root.querySelectorAll('.open-base-item').forEach(button=>button.onclick=()=>{const item=data.items.find(entry=>entry.key===`base:${button.dataset.itemId}`);if(item)openCatalogItem(item.key)});root.querySelectorAll('.open-blessing').forEach(button=>button.onclick=()=>{showPage('blessings');document.getElementById('blessing-search').value=button.dataset.blessingId;renderBlessings()})}
function renderEnchantments(){const q=norm(document.getElementById('enchantment-search').value),items=data.enchantments.filter(item=>!q||[item.name,item.inGameName,item.id,item.summary,item.activation,item.scaling,...item.effectTriggers,...item.items].some(value=>norm(value).includes(q)));const root=document.getElementById('enchantment-results');root.innerHTML=items.map(enchantmentCard).join('')||'<div class="empty">No enchantments match this search.</div>';wireEnchantments(root);document.getElementById('enchantment-stats').textContent=`Showing ${items.length} of ${data.enchantments.length} custom enchantments`}
document.getElementById('enchantment-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(renderEnchantments,150)};document.getElementById('clear-enchantments').onclick=()=>{document.getElementById('enchantment-search').value='';renderEnchantments()};
function blessingCard(item){const recipe=data.recipes.find(entry=>entry.id===item.recipeId);return `<details class="blessing-card"><summary><strong>${esc(item.name)}</strong><span>${item.enchantments.length} enchantments</span><code>${esc(item.id)}</code></summary><div class="blessing-body"><div class="blessing-enchants">${item.enchantments.map(enchantment=>enchantmentById.has(enchantment.id)?`<button class="open-enchantment" data-enchantment-id="${esc(enchantment.id)}">${esc(enchantment.name)} ${enchantment.level}</button>`:`<span>${esc(enchantment.name)} ${enchantment.level}</span>`).join('')}</div>${recipe?`<h3>Crafting recipe</h3>${card(recipe)}`:''}<p class="provenance">${esc(item.source)}</p></div></details>`}
function wireBlessings(root){root.querySelectorAll('.open-enchantment').forEach(button=>button.onclick=()=>{showPage('enchantments');document.getElementById('enchantment-search').value=button.dataset.enchantmentId;renderEnchantments()});wire(root)}
function renderBlessings(){const q=norm(document.getElementById('blessing-search').value),items=data.blessings.filter(item=>spoilerAllowed('blessing',item.id)&&(!q||norm(item.name).includes(q)||norm(item.id).includes(q)||item.enchantments.some(enchantment=>norm(enchantment.name).includes(q)||norm(enchantment.id).includes(q))));const root=document.getElementById('blessing-results');root.innerHTML=items.map(blessingCard).join('')||(spoilerMode!=='complete'?spoilerGate('blessing',data.blessings[0]?.id):'<div class="empty">No Blessings match this search.</div>');wireBlessings(root);document.getElementById('blessing-stats').textContent=`Showing ${items.length} of ${data.blessings.length} Blessings`}
document.getElementById('blessing-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(renderBlessings,150)};document.getElementById('clear-blessings').onclick=()=>{document.getElementById('blessing-search').value='';renderBlessings()};
function optimumPickList(entries,className){return entries.length?`<ul class="optimum-list">${entries.map(entry=>`<li><button class="${className}" data-optimum-id="${esc(entry.id??entry.key)}">${esc(entry.name)}</button><p>${esc(entry.reason)}</p></li>`).join('')}</ul>`:'<p class="empty">None picked for this section.</p>'}
function optimumPersonaCard(persona){const visibleBlessings=persona.blessings.filter(entry=>spoilerAllowed('blessing',entry.id));const enchantments=persona.enchantments.length?`<h3>Enchantments</h3>${optimumPickList(persona.enchantments,'open-enchantment')}`:'';const blessings=visibleBlessings.length?`<h3>Blessings</h3>${optimumPickList(visibleBlessings,'open-blessing')}`:'';const consumables=persona.consumables&&persona.consumables.length?`<h3>Consumables</h3>${optimumPickList(persona.consumables.map(entry=>({...entry,id:entry.key})),'food-item-link')}`:'';return `<article class="optimum-persona"><h2>${esc(persona.title)}</h2><p class="sub">${esc(persona.summary)}</p>${enchantments}${blessings}${consumables}</article>`}
function wireOptimumBuilds(root){root.querySelectorAll('.open-enchantment').forEach(button=>button.onclick=()=>{showPage('enchantments');document.getElementById('enchantment-search').value=button.dataset.optimumId;renderEnchantments()});root.querySelectorAll('.open-blessing').forEach(button=>button.onclick=()=>{showPage('blessings');document.getElementById('blessing-search').value=button.dataset.optimumId;renderBlessings()});root.querySelectorAll('.food-item-link').forEach(button=>button.onclick=()=>openFoodItem(button.dataset.optimumId))}
function renderOptimumBuilds(){const root=document.getElementById('optimum-builds-results');const personas=data.optimumBuilds.personas.map(optimumPersonaCard).join('');const allAround=data.optimumBuilds.allAround,allAroundHtml=allAround?optimumPersonaCard({title:allAround.title,summary:allAround.summary,enchantments:allAround.enchantments,blessings:allAround.blessings,consumables:[]}):'';root.innerHTML=personas+allAroundHtml||'<div class="empty">No curated Optimum Builds data is available.</div>';wireOptimumBuilds(root)}
const advancementById=new Map(data.advancements.map(item=>[item.id,item]));
function advancementCard(item){const icon=item.icon||data.items.find(candidate=>candidate.id===item.iconId&&candidate.icon)?.icon;return `<article class="advancement-card frame-${esc(item.frame)} ${item.hidden?'hidden-advancement':''}">${icon?`<img class="advancement-icon" loading="lazy" src="${esc(icon)}" alt="">`:'<span></span>'}<div><b>${esc(item.title)}</b><p>${esc(item.description||'No description supplied by the pack.')}</p><small>${esc(item.section)}${item.hidden?' | hidden advancement':''}</small></div><code>${esc(item.id)}</code></article>`}
function renderAdvancements(){const q=norm(document.getElementById('advancement-search').value),section=document.getElementById('advancement-section').value,items=data.advancements.filter(item=>spoilerAllowed('advancement',item.id)&&(!section||item.section===section)&&(!q||[item.title,item.description,item.id,item.parent].some(value=>norm(value).includes(q))));document.getElementById('advancement-results').innerHTML=items.map(advancementCard).join('')||'<div class="empty">No visible advancements match these filters.</div>';document.getElementById('advancement-stats').textContent=`Showing ${items.length} of ${data.advancements.length} advancement entries`}
function openAdvancement(id){const item=advancementById.get(id);if(!item)return;showPage('progression');document.getElementById('advancement-search').value=id;renderAdvancements();document.getElementById('advancement-results').scrollIntoView({behavior:'smooth'})}
function renderProgressionPath(){const root=document.getElementById('progression-path');root.className='progression-path';root.innerHTML=data.progression.map((stage,index)=>{const stageNumber=index+1;if(spoilerMode!=='complete'&&stageNumber>spoilerLimit())return `<article class="progression-stage"><h2>Stage ${stageNumber}</h2>${spoilerGate('advancement',stage.advancements[0])}</article>`;const milestones=stage.advancements.map(id=>{const item=advancementById.get(id);return item&&spoilerAllowed('advancement',id)?`<button data-advancement-id="${esc(id)}">${esc(item.title)}</button>`:''}).join('');return `<article class="progression-stage"><h2>${esc(stage.title)}</h2><p>${esc(stage.summary)}</p><div class="milestone-links">${milestones}</div></article>`}).join('');root.querySelectorAll('[data-advancement-id]').forEach(button=>button.onclick=()=>openAdvancement(button.dataset.advancementId))}
const advancementSections=[...new Set(data.advancements.map(item=>item.section))].sort();document.getElementById('advancement-section').innerHTML+=advancementSections.map(value=>`<option value="${esc(value)}">${esc(value.replaceAll('_',' '))}</option>`).join('');document.getElementById('advancement-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(renderAdvancements,150)};document.getElementById('advancement-section').onchange=renderAdvancements;document.getElementById('clear-advancements').onclick=()=>{document.getElementById('advancement-search').value='';document.getElementById('advancement-section').value='';renderAdvancements()};
const releaseHistory=data.releaseHistory;
function releaseCard(item){const date=item.published?new Date(item.published).toLocaleDateString():'',details=spoilerMode==='complete'?(item.changelog?`<pre>${esc(item.changelog)}</pre>`:'<div class="empty">No changelog was published for this release.</div>'):spoilerGate('release',item.id);return `<details class="release-card" ${item.current?'open':''}><summary><span><strong>${esc(item.version)}</strong> ${item.current?'<span class="current-release">current ZIP</span>':''}</span><span>${spoilerMode==='complete'?esc(item.name):'Release details hidden'}</span><span class="release-type ${esc(item.type)}">${esc(item.type)}</span><time>${esc(date)}</time></summary><div class="release-body"><div class="release-games">Minecraft ${item.gameVersions.map(esc).join(', ')}</div>${details}</div></details>`}
function comparisonGroup(group){const sections=['added','removed','changed'].map(state=>group[state].length?`<details><summary>${state[0].toUpperCase()+state.slice(1)} (${group[state].length})</summary><ul>${group[state].map(item=>`<li><code>${esc(item.id)}</code><small>${esc(item.path)}</small></li>`).join('')}</ul></details>`:'').join('');return `<article class="comparison-group"><h3>${esc(group.name)}</h3>${sections}</article>`}
function renderReleases(){if(!releaseHistory){document.getElementById('release-summary').innerHTML='<div class="empty">This build does not include Modrinth metadata. Rebuild with --modrinth-project to add it.</div>';document.getElementById('version-comparison').innerHTML='';document.getElementById('release-results').innerHTML='';document.getElementById('release-stats').textContent='';return}const q=norm(document.getElementById('release-search').value),type=document.getElementById('release-type').value,releases=releaseHistory.releases.filter(item=>(!type||item.type===type)&&(!q||(spoilerMode==='complete'?[item.version,item.name,item.type,item.changelog,...item.gameVersions]:[item.version,item.type,...item.gameVersions]).some(value=>norm(value).includes(q))));document.getElementById('release-summary').innerHTML=`<div class="release-summary"><div><b>Official source</b><a href="${esc(releaseHistory.project.url)}" target="_blank" rel="noopener">${esc(releaseHistory.project.title)}</a></div><div><b>Current ZIP</b>${esc(releaseHistory.currentVersion||'Not matched')}</div><div><b>Latest stable</b>${esc(releaseHistory.latestStable||'Unknown')}</div><div><b>Latest published</b>${esc(releaseHistory.latestPublished||'Unknown')}</div></div>`;const comparison=releaseHistory.comparison;if(comparison&&spoilerMode==='complete'){const summary=comparison.summary;document.getElementById('version-comparison').innerHTML=`<h2>ZIP comparison: ${esc(comparison.baselineVersion)} to ${esc(comparison.currentVersion)}</h2><div class="comparison-summary"><span>${summary.added} added</span><span>${summary.removed} removed</span><span>${summary.changed} changed</span><span>${summary.unchanged} unchanged</span></div><div class="comparison-grid">${comparison.categories.map(comparisonGroup).join('')}</div>`}else if(comparison)document.getElementById('version-comparison').innerHTML=spoilerGate('release','comparison');else document.getElementById('version-comparison').innerHTML='<div class="empty">No earlier stable release was available for comparison.</div>';document.getElementById('release-results').innerHTML=releases.map(releaseCard).join('')||'<div class="empty">No releases match these filters.</div>';document.getElementById('release-stats').textContent=`Showing ${releases.length} of ${releaseHistory.releases.length} published versions`}
document.getElementById('release-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(renderReleases,150)};document.getElementById('release-type').onchange=renderReleases;document.getElementById('clear-releases').onclick=()=>{document.getElementById('release-search').value='';document.getElementById('release-type').value='';renderReleases()};
function differenceCard(item){return `<article class="difference-card"><span class="category">${esc(item.category)}</span> <span class="provenance-badge">${esc(item.provenance)}</span><h2>${esc(item.title)}</h2><p>${esc(item.summary)}</p><div class="source-citations">${item.sources.map(source=>`<code>${esc(source)}</code>`).join('')}</div></article>`}
function renderDifferences(){const q=norm(document.getElementById('difference-search').value),category=document.getElementById('difference-category').value,items=data.differences.filter(item=>spoilerAllowed('difference',item.title)&&(!category||item.category===category)&&(!q||[item.category,item.title,item.summary,...item.sources].some(value=>norm(value).includes(q))));document.getElementById('difference-results').className='difference-grid';document.getElementById('difference-results').innerHTML=items.map(differenceCard).join('')||'<div class="empty">No visible changes match these filters.</div>';document.getElementById('difference-stats').textContent=`Showing ${items.length} of ${data.differences.length} documented changes`}
const differenceCategories=[...new Set(data.differences.map(item=>item.category))].sort();document.getElementById('difference-category').innerHTML+=differenceCategories.map(value=>`<option value="${esc(value)}">${esc(value)}</option>`).join('');document.getElementById('difference-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(renderDifferences,150)};document.getElementById('difference-category').onchange=renderDifferences;document.getElementById('clear-differences').onclick=()=>{document.getElementById('difference-search').value='';document.getElementById('difference-category').value='';renderDifferences()};
function globalGroup(title,total,content){return total?`<section class="search-group"><h2>${title}<span class="count">${total} found${total>12?' | first 12 shown':''}</span></h2>${content}</section>`:''}
function runGlobalSearch(){
 const q=norm(document.getElementById('global-search').value),root=document.getElementById('global-results');if(!q){root.innerHTML='<div class="empty global-empty">Enter a search term.</div>';document.getElementById('global-stats').textContent='';return}
 activeQuery=q;
 const items=data.items.filter(item=>spoilerAllowed('item',item.key)&&[item.name,item.id,...item.lore,...item.properties].some(value=>norm(value).includes(q)));
 const recipes=data.recipes.filter(recipe=>spoilerAllowed('recipe',recipe.id)&&norm(recipe.search).includes(q));
 const foods=data.foodItems.filter(item=>norm(item.name).includes(q)||norm(item.underlyingId).includes(q)||item.effects.some(effect=>norm(effect.name).includes(q)||norm(effect.id).includes(q))||item.removes.some(effect=>norm(effect.name).includes(q)));
 const enchantments=data.enchantments.filter(item=>[item.name,item.inGameName,item.id,item.summary,item.activation,item.scaling,...item.effectTriggers,...item.items,...item.functions.flatMap(fn=>fn.commands)].some(value=>norm(value).includes(q)));
 const blessings=data.blessings.filter(item=>spoilerAllowed('blessing',item.id)&&(norm(item.name).includes(q)||norm(item.id).includes(q)||item.enchantments.some(enchantment=>norm(enchantment.name).includes(q)||norm(enchantment.id).includes(q))));
 const sourceRecords=data.acquisition.filter(item=>item.sources.some(source=>!['Chest loot','Archaeology'].includes(source.kind)&&(norm(source.kind).includes(q)||norm(source.location).includes(q)||norm(source.id).includes(q))));
 const sourceItems=[...new Map(sourceRecords.map(record=>{const item=catalogByKey.get(`base:${record.id}`);return item?[item.key,item]:[record.id,null]}).filter(([,item])=>item&&spoilerAllowed('item',item.key))).values()];
 const mechanics=data.mechanics.filter(name=>norm(name).includes(q));
 const advancements=data.advancements.filter(item=>spoilerAllowed('advancement',item.id)&&[item.title,item.description,item.id,item.section].some(value=>norm(value).includes(q)));
 const differences=data.differences.filter(item=>spoilerAllowed('difference',item.title)&&[item.category,item.title,item.summary,...item.sources].some(value=>norm(value).includes(q)));
 const trades=data.trades.filter(trade=>spoilerAllowed('trade',trade.id)&&[trade.id,trade.profession,trade.level,trade.result.id,trade.result.name,...trade.costs.flatMap(item=>[item.id,item.name]),...trade.bundleContents.flatMap(item=>[item.id,item.name])].some(value=>norm(value).includes(q)));
 const places=allPlaces.filter(item=>spoilerAllowed('place',item.id)&&item.kind!=='Archaeology'&&[item.name,item.id,item.kind,item.type,item.step,item.terrainAdaptation,item.startPool,item.biomeSelector,...(item.biomes||[]),...(item.items||[]).flatMap(entry=>[entry.id,entry.name])].some(value=>norm(value).includes(q)));
 const archaeology=data.archaeology.filter(site=>[site.name,site.id,site.tableType,...site.entries.flatMap(entry=>[entry.name,entry.id,...entry.resolvedItems.flatMap(item=>[item.name,item.id])])].some(value=>norm(value).includes(q)));
 const fishing=data.fishing.tables.filter(record=>[record.name,record.id,record.role,...record.biomeSelectors,...record.biomes,...record.entries.flatMap(entry=>[entry.name,entry.id,...entry.conditions,...entry.modifiers,...entry.resolvedItems.flatMap(item=>[item.name,item.id])])].some(value=>norm(value).includes(q)));
 const releases=releaseHistory?releaseHistory.releases.filter(item=>(spoilerMode==='complete'?[item.version,item.name,item.type,item.changelog,...item.gameVersions]:[item.version,item.type,...item.gameVersions]).some(value=>norm(value).includes(q))):[];
 const total=items.length+recipes.length+foods.length+enchantments.length+blessings.length+sourceItems.length+mechanics.length+advancements.length+differences.length+trades.length+places.length+archaeology.length+fishing.length+releases.length;
 root.innerHTML=globalGroup('Items',items.length,`<div class="item-grid">${items.slice(0,12).map(catalogCard).join('')}</div>`)+globalGroup('Recipes',recipes.length,recipes.slice(0,12).map(card).join(''))+globalGroup('Food and effects',foods.length,foods.slice(0,12).map(foodCard).join(''))+globalGroup('Villager trades',trades.length,trades.slice(0,12).map(tradeCard).join(''))+globalGroup('Places and structures',places.length,places.slice(0,12).map(placeCard).join(''))+globalGroup('Archaeology',archaeology.length,archaeology.slice(0,12).map(archaeologyCard).join(''))+globalGroup('Fishing',fishing.length,fishing.slice(0,12).map(fishingRecordCard).join(''))+globalGroup('Releases',releases.length,releases.slice(0,12).map(releaseCard).join(''))+globalGroup('Enchantments',enchantments.length,enchantments.slice(0,12).map(enchantmentCard).join(''))+globalGroup('Blessings',blessings.length,blessings.slice(0,12).map(blessingCard).join(''))+globalGroup('Progression advancements',advancements.length,advancements.slice(0,12).map(advancementCard).join(''))+globalGroup('Differences from Vanilla',differences.length,`<div class="difference-grid">${differences.slice(0,12).map(differenceCard).join('')}</div>`)+globalGroup('Other acquisition sources',sourceItems.length,`<div class="item-grid">${sourceItems.slice(0,12).map(catalogCard).join('')}</div>`)+globalGroup('Mechanics',mechanics.length,`<div class="search-group-grid">${mechanics.map(name=>`<div class="search-hit"><b>${esc(name)}</b><small>Gameplay mechanic</small></div>`).join('')}</div>`)||'<div class="empty">No results found.</div>';
 document.getElementById('global-stats').textContent=`${total} results across the wiki`;
 wireCatalog(root);wire(root);wireFoodLinks(root);wireEnchantments(root);wireBlessings(root);wirePlaces(root);wireArchaeology(root);wireFishing(root)
}
document.getElementById('global-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(runGlobalSearch,150)};document.getElementById('clear-global').onclick=()=>{document.getElementById('global-search').value='';runGlobalSearch()};
function refreshSpoilers(){renderSpoilerDatalists();search();filterItems();filterTrades();filterPlaces();renderEnchantments();renderBlessings();renderOptimumBuilds();renderAdvancements();renderProgressionPath();renderReleases();renderDifferences();if(document.getElementById('reverse-search').value.trim())reverse();if(document.getElementById('obtain-search').value.trim())obtain();if(document.getElementById('global-search').value)runGlobalSearch()}
const categories=[...new Set(data.recipes.map(r=>r.namespace))].sort();document.getElementById('category').innerHTML+=[...categories].map(x=>`<option value="${esc(x)}">${esc(x.replaceAll('_',' '))}</option>`).join('');
document.getElementById('ibox-recipes').textContent=data.recipes.length.toLocaleString();document.getElementById('ibox-foods').textContent=data.foodItems.length;document.getElementById('ibox-trades').textContent=data.trades.length;document.getElementById('ibox-enchants').textContent=data.enchantments.length;const counts={};data.recipes.forEach(r=>counts[r.namespace]=(counts[r.namespace]||0)+1);document.getElementById('summary').innerHTML='<table class="wikitable"><tr><th>Recipe group</th><th>Count</th></tr>'+Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<tr><td>${esc(k.replaceAll('_',' '))}</td><td>${v}</td></tr>`).join('')+'</table>';
document.getElementById('mechanic-list').innerHTML='<ul>'+data.mechanics.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>';document.getElementById('override-table').innerHTML='<table class="wikitable"><tr><th>Data type</th><th>Files</th></tr>'+data.overrides.sort((a,b)=>b.count-a.count).map(x=>`<tr><td><code>${esc(x.type)}</code></td><td>${x.count}</td></tr>`).join('')+'</table>';
renderSpoilerDatalists();search();filterTrades();filterPlaces();renderArchaeology();renderFishingRoutes();renderFishing();renderFoods();filterItems();renderEnchantments();renderBlessings();renderOptimumBuilds();renderAdvancements();renderProgressionPath();renderReleases();renderDifferences();showPage(location.hash.slice(1)||'overview',false);
