
const data=window.MATCHA_DATA, PAGE_SIZE=40;let page=1,activeQuery='',filtered=[],matchedSearchItems=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').toLowerCase().trim();
const itemMatch=(x,q=activeQuery)=>q&&(norm(x.id).includes(q)||norm(x.name).includes(q));
function showPage(id,updateHash=true){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.side button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(updateHash&&location.hash!==`#${id}`)location.hash=id;scrollTo(0,0)}
document.querySelectorAll('.side button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
window.addEventListener('hashchange',()=>showPage(location.hash.slice(1)||'overview',false));
function slot(i,count=1){if(!i)return '<span class="slot"></span>';const visual=i.icon?`<img loading="lazy" src="${esc(i.icon)}" alt="${esc(i.name)}">`:`<span class="slot-fallback">${esc(i.name)}</span>`;return `<span class="slot" title="${esc(i.name)} (${esc(i.id)})">${visual}${count>1?`<span class="slot-count">${count}</span>`:''}</span>`}
function diagram(r){let input;if(r.type==='crafting_shaped'){const map={};r.ingredients.forEach(i=>map[i.symbol]=i);const rows=r.pattern.map(x=>x.padEnd(3,' '));while(rows.length<3)rows.push('   ');input=`<div class="craft-grid">${rows.flatMap(x=>[...x]).map(x=>slot(map[x])).join('')}</div>`}else if(r.type==='crafting_shapeless'){const items=[...r.ingredients];while(items.length<9)items.push(null);input=`<div class="craft-grid">${items.slice(0,9).map(i=>slot(i,i?.count)).join('')}</div>`}else input=`<div class="ingredients">${r.ingredients.map(i=>slot(i,i.count)).join('')}</div>`;return `<div class="visual-label">${esc(r.patternLabel)}</div><div class="recipe-visual">${input}<span class="arrow">➜</span>${slot({id:r.resultId,name:r.resultName,icon:r.icon},r.count)}</div>`}
function ingredient(i){return `<button class="ingredient ${itemMatch(i)?'matched':''}" data-lookup="${esc(i.id)}">${esc(i.name)}${i.count>1?' x'+i.count:''}</button>`}
function effectBadge(effect){const chance=effect.probability<1?` ${Math.round(effect.probability*100)}%`:'';return `<span class="effect ${esc(effect.category)}">${esc(effect.name)} ${effect.level} ${esc(effect.duration)}${chance}</span>`}
function foodBadges(food){if(!food)return '';const effects=food.effects.map(effectBadge);if(food.clearAll)effects.push('<span class="effect cleansing">Clears all effects</span>');if(food.removes.length)effects.push(`<span class="effect cleansing">Removes ${food.removes.length} harmful effects</span>`);return effects.length?`<div class="effect-badges">${effects.join('')}</div>`:''}
function foodDetails(food){if(!food)return '';const facts=[['Nutrition',food.nutrition??'Not specified'],['Saturation',food.saturation??'Not specified'],['Always edible',food.alwaysEdible?'Yes':'No'],['Consume time',food.consumeSeconds!=null?food.consumeSeconds+'s':'Default'],['Animation',food.animation||'Default'],['Remainder',food.remainder||'None']];const effects=food.effects.length?`<table class="effect-table"><tr><th>Effect</th><th>Level</th><th>Duration</th><th>Chance</th><th>Type</th></tr>${food.effects.map(e=>`<tr><td>${esc(e.name)}</td><td>${e.level}</td><td>${esc(e.duration)}</td><td>${Math.round(e.probability*100)}%</td><td><span class="effect ${esc(e.category)}">${esc(e.category)}</span></td></tr>`).join('')}</table>`:'<p>No status effects are applied.</p>';const cleansing=food.clearAll?'<p><span class="effect cleansing">Clears all active status effects</span></p>':food.removes.length?`<p><span class="effect cleansing">Removes:</span> ${food.removes.map(e=>esc(e.name)).join(', ')}</p>`:'';return `<section class="food-details"><h2>Food properties</h2><div class="food-facts">${facts.map(([k,v])=>`<div class="food-fact"><b>${esc(k)}</b>${esc(v)}</div>`).join('')}</div><h3>Effects when consumed</h3>${effects}${cleansing}</section>`}
function card(r){const resultMatch=itemMatch({id:r.resultId,name:r.resultName})?' matched':'',food=r.foodKey?foodByKey.get(r.foodKey):null;return `<article class="recipe"><img class="icon" loading="lazy" src="${esc(r.icon)}" alt=""><div class="result${resultMatch}"><b>${esc(r.resultName)}</b>${r.count>1?' x'+r.count:''} ${r.custom?'<span class="custom">custom item</span>':''}<div class="id">${esc(r.resultId)}</div>${foodBadges(food)}</div><div class="ingredients">${r.ingredients.map(ingredient).join('')}</div><div class="type">${esc(r.patternLabel)}<br><small>click for diagram and effects</small></div><div class="detail">${diagram(r)}${foodDetails(food)}<p><b>Recipe ID:</b> <code>${esc(r.id)}</code><br><b>Recipe type:</b> <code>${esc(r.type)}</code></p></div></article>`}
function wire(root){root.querySelectorAll('.recipe').forEach(x=>x.onclick=e=>{if(!e.target.closest('.ingredient'))x.classList.toggle('open')});root.querySelectorAll('.ingredient').forEach(x=>x.onclick=()=>{showPage('reverse');document.getElementById('reverse-search').value=x.dataset.lookup;reverse()})}
function searchItemHTML(item){const icon=item.icon||iconMap.get(item.id),key=item.key||item.id,id=item.underlyingId||item.id;return `<button class="search-item-card" data-obtain-id="${esc(key)}">${icon?`<img src="${esc(icon)}" alt="">`:''}<span><b>${esc(item.name)}</b><code>${esc(id)}</code>${item.key?foodBadges(item):''}<small>View item information</small></span></button>`}
function wireSearchItems(root){root.querySelectorAll('.search-item-card').forEach(button=>button.onclick=()=>{showPage('obtaining');document.getElementById('obtain-search').value=button.dataset.obtainId;obtain()})}
function renderPage(){const start=(page-1)*PAGE_SIZE,end=start+PAGE_SIZE,root=document.getElementById('all-results');const items=matchedSearchItems.length?`<section class="matching-items"><h2>Matching items <span class="count">${matchedSearchItems.length}</span></h2>${matchedSearchItems.slice(0,20).map(searchItemHTML).join('')}</section>`:'';const recipes=filtered.slice(start,end).map(card).join('')||'<div class="empty">No matching recipes.</div>';root.innerHTML=items+recipes;wireSearchItems(root);wire(root);const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));document.getElementById('pager').innerHTML=`<button id="prev" ${page===1?'disabled':''}>Previous</button><span>Page ${page} of ${pages}</span><button id="next" ${page===pages?'disabled':''}>Next</button>`;document.getElementById('prev').onclick=()=>{page--;renderPage();scrollTo(0,0)};document.getElementById('next').onclick=()=>{page++;renderPage();scrollTo(0,0)}}
function search(){activeQuery=norm(document.getElementById('all-search').value);const category=document.getElementById('category').value;let pool=data.recipes.filter(r=>!category||r.namespace===category);if(activeQuery){const baseItems=data.acquisition.filter(item=>norm(item.id).includes(activeQuery)||norm(item.name).includes(activeQuery));const foods=data.foodItems.filter(item=>norm(item.underlyingId).includes(activeQuery)||norm(item.name).includes(activeQuery)||item.effects.some(e=>norm(e.name).includes(activeQuery)));matchedSearchItems=[...baseItems,...foods].sort((a,b)=>(norm(a.id||a.underlyingId)===activeQuery||norm(a.name)===activeQuery?-1:0)-(norm(b.id||b.underlyingId)===activeQuery||norm(b.name)===activeQuery?-1:0));const creates=pool.filter(r=>itemMatch({id:r.resultId,name:r.resultName}));const uses=pool.filter(r=>r.ingredients.some(i=>itemMatch(i))&&!creates.includes(r));const related=pool.filter(r=>r.search.includes(activeQuery)&&!creates.includes(r)&&!uses.includes(r));filtered=[...creates,...uses,...related];document.getElementById('all-stats').textContent=`${matchedSearchItems.length} matching items; ${creates.length} recipes create them; ${uses.length} recipes use them; ${related.length} other matches.`}else{matchedSearchItems=[];filtered=pool;document.getElementById('all-stats').textContent=`${filtered.length.toLocaleString()} recipes. Only ${PAGE_SIZE} render at a time.`}page=1;renderPage()}
let timer;document.getElementById('all-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(search,150)};document.getElementById('category').onchange=search;document.getElementById('clear-all').onclick=()=>{document.getElementById('all-search').value='';document.getElementById('category').value='';search()};
function group(title,list,empty){const shown=list.slice(0,100),notice=list.length>100?`<div class="stats">Showing the first 100 exact or related matches. Refine the item name to narrow this list.</div>`:'';return `<section class="group"><h2>${title}<span class="count">${list.length} recipe${list.length===1?'':'s'}</span></h2>${notice}${shown.length?shown.map(card).join(''):`<div class="empty">${empty}</div>`}</section>`}
function reverse(){const raw=document.getElementById('reverse-search').value,q=norm(raw);if(!q)return;const exact=[...itemMap].find(([id,name])=>norm(id)===q||norm(name)===q),target=exact?.[0];activeQuery=target?norm(target):q;const matches=x=>target?x.id===target:itemMatch(x);const made=data.recipes.filter(r=>matches({id:r.resultId,name:r.resultName}));const used=data.recipes.filter(r=>r.ingredients.some(matches));const root=document.getElementById('reverse-results');root.innerHTML=`<div class="reversehead"><b>${esc(raw)}</b>: produced by ${made.length}; used by ${used.length}.</div>`+group('Recipe for this item',made,'No recipe produces this item.')+group('Recipes using this item',used,'No recipe consumes this item.');wire(root)}
document.getElementById('reverse-go').onclick=reverse;document.getElementById('reverse-search').onkeydown=e=>{if(e.key==='Enter')reverse()};
const itemMap=new Map();data.recipes.forEach(r=>{itemMap.set(r.resultId,r.resultName);r.ingredients.forEach(i=>itemMap.set(i.id,i.name))});document.getElementById('item-list').innerHTML=[...itemMap].map(([id,name])=>`<option value="${esc(name)}">${esc(id)}</option>`).join('');
const canonical=id=>String(id).includes(':')?String(id):'minecraft:'+id;
const iconMap=new Map();data.recipes.forEach(r=>{if(r.icon)iconMap.set(canonical(r.resultId),r.icon);r.ingredients.forEach(i=>{if(i.icon)iconMap.set(canonical(i.id),i.icon)})});
const acquisitionMap=new Map(data.acquisition.map(item=>[item.id,item]));
const foodByKey=new Map(data.foodItems.map(item=>[item.key,item]));
document.getElementById('obtain-item-list').innerHTML=[...data.acquisition.map(item=>`<option value="${esc(item.name)}">${esc(item.id)}</option><option value="${esc(item.id)}">${esc(item.name)}</option>`),...data.foodItems.map(item=>`<option value="${esc(item.name)}">${esc(item.underlyingId)}</option>`)].join('');
function acquisitionSources(item){
 const recipes=item.recipes.length?`<h2>Recipes</h2><div class="source-list">${item.recipes.map(id=>`<div class="source"><b>Crafting or processing</b><code>${esc(id)}</code></div>`).join('')}</div>`:'';
 const loot=item.sources.length?`<h2>Loot and world sources</h2><div class="source-list">${item.sources.map(source=>`<div class="source"><b>${esc(source.kind)}</b>${esc(source.location)}<br><code>${esc(source.id)}</code></div>`).join('')}</div>`:'';
 const trades=item.trades.length?`<h2>Villager trades</h2><div class="source-list">${item.trades.map(trade=>`<div class="source"><b>${esc(trade.profession)} (${esc(trade.level)})</b>Cost: ${esc(trade.cost)}${trade.container?`<br>Contained in: ${esc(trade.container)}`:''}<br><code>${esc(trade.id)}</code></div>`).join('')}</div>`:'';
 const none=!item.recipes.length&&!item.sources.length&&!item.trades.length?'<div class="empty">No pack-defined acquisition source was found. This item may retain its normal vanilla source.</div>':'';
 const wiki=item.wiki?`<a class="wiki-link" href="${esc(item.wiki)}" target="_blank" rel="noopener">Open vanilla item on Minecraft Wiki</a>`:'';
 const icon=iconMap.get(item.id);
 return `<article class="acq-card"><div class="acq-head">${icon?`<img src="${esc(icon)}" alt="">`:''}<div><h2>${esc(item.name)}</h2><code>${esc(item.id)}</code></div></div>${recipes}${loot}${trades}${none}${wiki}</article>`
}
function foodAcquisition(item){const recipes=item.recipes.map(id=>data.recipes.find(recipe=>recipe.id===id)).filter(Boolean);return `<article class="acq-card"><div class="acq-head"><img src="${esc(item.icon)}" alt=""><div><h2>${esc(item.name)}</h2><code>${esc(item.underlyingId)}</code></div></div>${foodDetails(item)}<h2>How to make this item</h2><div class="food-item-recipes">${recipes.map(card).join('')}</div><p class="stats">This custom item uses ${esc(item.underlyingId)} as its underlying vanilla carrier. It is identified separately by its custom name, model, food properties, and consumable effects.</p></article>`}
function wireAcquisitionChoices(root){root.querySelectorAll('.item-choice').forEach(button=>button.onclick=()=>{document.getElementById('obtain-search').value=button.dataset.id;obtain()})}
function obtain(){
 const raw=document.getElementById('obtain-search').value.trim(),q=norm(raw);if(!q)return;
 const exactFood=data.foodItems.find(item=>norm(item.key)===q||norm(item.name)===q);
 const exact=data.acquisition.find(item=>norm(item.id)===q||norm(item.name)===q);
 const root=document.getElementById('obtain-results');
 if(exactFood){root.innerHTML=foodAcquisition(exactFood);wire(root);return}
 if(exact){root.innerHTML=acquisitionSources(exact);return}
 const matches=[...data.foodItems.filter(item=>norm(item.underlyingId).includes(q)||norm(item.name).includes(q)).map(item=>({id:item.key,name:item.name,detail:item.underlyingId})),...data.acquisition.filter(item=>norm(item.id).includes(q)||norm(item.name).includes(q)).map(item=>({id:item.id,name:item.name,detail:item.id}))].slice(0,100);
 root.innerHTML=matches.length?`<div class="reversehead">${matches.length} matching items. Select one for its acquisition details.</div>${matches.map(item=>`<button class="item-choice" data-id="${esc(item.id)}"><b>${esc(item.name)}</b><br><code>${esc(item.detail)}</code></button>`).join('')}`:'<div class="empty">No matching item was found.</div>';
 wireAcquisitionChoices(root)
}
document.getElementById('obtain-go').onclick=obtain;document.getElementById('obtain-search').onkeydown=e=>{if(e.key==='Enter')obtain()};
let foodPage=1,foodFiltered=data.foodItems;const FOOD_PAGE_SIZE=24;
function foodCard(item){return `<article class="food-card"><button class="food-item-link food-image-link" data-food-key="${esc(item.key)}" title="Open ${esc(item.name)} item page"><img loading="lazy" src="${esc(item.icon)}" alt="${esc(item.name)}"></button><div><button class="food-item-link food-name-link" data-food-key="${esc(item.key)}">${esc(item.name)}</button><div class="id">${esc(item.underlyingId)}</div><div class="stats">${item.recipes.length} recipe${item.recipes.length===1?'':'s'}</div></div><div>${foodBadges(item)}<details><summary>Quick food properties</summary>${foodDetails(item)}</details></div></article>`}
function openFoodItem(key){const item=foodByKey.get(key);if(!item)return;showPage('obtaining');document.getElementById('obtain-search').value=item.name;document.getElementById('obtain-results').innerHTML=foodAcquisition(item);wire(document.getElementById('obtain-results'))}
function wireFoodLinks(root){root.querySelectorAll('.food-item-link').forEach(link=>link.onclick=()=>openFoodItem(link.dataset.foodKey))}
function renderFoods(){const start=(foodPage-1)*FOOD_PAGE_SIZE,pages=Math.max(1,Math.ceil(foodFiltered.length/FOOD_PAGE_SIZE)),root=document.getElementById('food-results');root.innerHTML=foodFiltered.slice(start,start+FOOD_PAGE_SIZE).map(foodCard).join('')||'<div class="empty">No foods match these filters.</div>';wireFoodLinks(root);document.getElementById('food-stats').textContent=`Showing ${foodFiltered.length} of ${data.foodItems.length} distinct food variants`;document.getElementById('food-pager').innerHTML=`<button id="food-prev" ${foodPage===1?'disabled':''}>Previous</button><span>Page ${foodPage} of ${pages}</span><button id="food-next" ${foodPage===pages?'disabled':''}>Next</button>`;document.getElementById('food-prev').onclick=()=>{foodPage--;renderFoods();scrollTo(0,0)};document.getElementById('food-next').onclick=()=>{foodPage++;renderFoods();scrollTo(0,0)}}
function filterFoods(){const q=norm(document.getElementById('food-search').value),effect=document.getElementById('effect-filter').value,kind=document.getElementById('effect-kind').value;foodFiltered=data.foodItems.filter(item=>(!q||norm(item.name).includes(q)||norm(item.underlyingId).includes(q)||item.effects.some(e=>norm(e.name).includes(q))||item.removes.some(e=>norm(e.name).includes(q)))&&(!effect||item.effects.some(e=>e.id===effect))&&(!kind||(kind==='cleansing'?(item.clearAll||item.removes.length):item.effects.some(e=>e.category===kind))));foodPage=1;renderFoods()}
document.getElementById('effect-filter').innerHTML+=data.foodEffects.map(([id,name])=>`<option value="${esc(id)}">${esc(name)}</option>`).join('');document.getElementById('food-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(filterFoods,150)};document.getElementById('effect-filter').onchange=filterFoods;document.getElementById('effect-kind').onchange=filterFoods;document.getElementById('clear-food').onclick=()=>{document.getElementById('food-search').value='';document.getElementById('effect-filter').value='';document.getElementById('effect-kind').value='';filterFoods()};
const categories=[...new Set(data.recipes.map(r=>r.namespace))].sort();document.getElementById('category').innerHTML+=[...categories].map(x=>`<option value="${esc(x)}">${esc(x.replaceAll('_',' '))}</option>`).join('');
document.getElementById('ibox-recipes').textContent=data.recipes.length.toLocaleString();document.getElementById('ibox-foods').textContent=data.foodItems.length;document.getElementById('ibox-enchants').textContent=data.enchantments.length;const counts={};data.recipes.forEach(r=>counts[r.namespace]=(counts[r.namespace]||0)+1);document.getElementById('summary').innerHTML='<table class="wikitable"><tr><th>Recipe group</th><th>Count</th></tr>'+Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<tr><td>${esc(k.replaceAll('_',' '))}</td><td>${v}</td></tr>`).join('')+'</table>';
document.getElementById('enchantment-table').innerHTML='<table class="wikitable"><tr><th>Name</th><th>ID</th><th>Max level</th><th>Slots</th></tr>'+data.enchantments.map(e=>`<tr><td>${esc(e.name)}</td><td><code>${esc(e.id)}</code></td><td>${e.max}</td><td>${e.slots.map(esc).join(', ')}</td></tr>`).join('')+'</table>';document.getElementById('mechanic-list').innerHTML='<ul>'+data.mechanics.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>';document.getElementById('override-table').innerHTML='<table class="wikitable"><tr><th>Data type</th><th>Files</th></tr>'+data.overrides.sort((a,b)=>b.count-a.count).map(x=>`<tr><td><code>${esc(x.type)}</code></td><td>${x.count}</td></tr>`).join('')+'</table>';
search();renderFoods();showPage(location.hash.slice(1)||'overview',false);
